1.6 metaprogramming
mcroitor/cpp_for_game_designers_ro pull request #11
Opened 2024-10-02 17:49 UTC by mcroitor

2024-10-02 18:59 UTC, cemti requested changes

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +Definirea unui șablon se începe cu construcția cheie `template<typename TYPE, ...>`, unde în parantezele unghiulare sunt specificate parametrii șablonului. Parametrii șablonului pot fi orice număr de
```suggestion
Definirea unui șablon se începe cu construcția cheie `template<typename TYPE, ...>`, unde în parantezele unghiulare sunt specificate parametrii șablonului. Numărul de parametrii șablonului poate fi orice.
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +> La definirea parametrilor tip ale sablonului În loc de cuvântul cheie `typename` se poate folosi cuvântul cheie `class`.
```suggestion
> La definirea parametrilor tip ale sablonului, în loc de cuvântul cheie `typename` se poate folosi cuvântul cheie `class`.
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +Parametrul șablonului de funcție poate fi orice tip de date, inclusiv un tip de date definit de utilizator, sau o valoare de tip enumerabil (de exemplu, `int`, `char` sau enumerare).
```suggestion
Parametrul șablonului de funcție poate fi orice tip de date, inclusiv unul definit de utilizator, sau o valoare de tip enumerabil (de exemplu, `int`, `char` sau enumerare).
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +Apel unei funcții șablon, în general, este similar cu apelul unei funcții obișnuite. În acest caz, compilatorul va deduce tipul `TYPE` parametrilor funcției din tipul argumentelor efective. În cazul
```suggestion
Apelul unei funcții șablon, în general, este similar cu apelul unei funcții obișnuite. În acest caz, compilatorul va deduce tipul `TYPE` parametrilor funcției din tipul argumentelor efective. În cazul în care tipurile argumentelor efective sunt diferite, compilatorul nu va putea deduce tipul parametrilor funcției și va genera o eroare, de exemplu:
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +Fiecare șablon de funcție presupune existența unor anumite proprietăți ale tipului de date parametrizat, în dependența de realizare (de exemplu, operatorul de copiere, operatorul de comparare, existe
```suggestion
Fiecare șablon de funcție presupune existența unor anumite proprietăți ale tipului de date parametrizat, în dependența de realizare (de exemplu, operatorul de copiere, operatorul de comparare, existența unui anumit metoda etc.). În standardul C++20, pentru aceasta sunt responsabile _conceptele_ [^2].
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +Terminul _instanțierea_ ( crearea unei instanțe) poate fi aplicat atât la declararea variabilelor, cât și la crearea implementărilor concrete ale funcțiilor sau claselor șablonice.
```suggestion
Terminul _instanțierea_ (crearea unei instanțe) poate fi aplicat atât la declararea variabilelor, cât și la crearea implementărilor concrete ale funcțiilor sau claselor șablonice.
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +```
```suggestion
```cpp
template<typename TYPE>
void print(TYPE p) {
  std::cout << p.toString() << std::endl;
}

template<>
void print(int p) {
  std::cout << p << std::endl;
}

template<>
void print(float p) {
  std::cout << p << std::endl;
}

template<>
void print(std::string p) {
  std::cout << p << std::endl;
}
```
```

2024-10-02 18:59 UTC, cemti commented on 16_metaprogramming.md
> +}
```suggestion
template<size_t N>
size_t fibbonacci()
{
    return fibbonacci<N - 1>() + fibbonacci<N - 2>();
}

template<>
size_t fibbonacci<0>()
{
    return 0;
}

template<>
size_t fibbonacci<1>()
{
    return 1;
}
```

`index` va fi înlocuit cu `N` pentru lizibilitate.

2024-10-06 07:50 UTC, mcroitor commented on 16_metaprogramming.md
> +}
Nu cred ca modificarea aceasta este esentiala.

2024-10-09 18:56 UTC, cemti approved these changes

2024-10-12 04:45 UTC, merged