Lab/01
mcroitor/cpp_for_game_designers_ro pull request #2
Opened 2024-09-04 11:18 UTC by mcroitor

2024-09-04 13:11 UTC, cemti requested changes
> 6. Creați fișiere `h` / `cpp` cu definirea structurilor de bază necesitate pentru proiect

După exemplul dat, s-au adăugat fișierele de antet `.hpp`, nu `.h`.
Este o cerință neclară să fie adăugate fișierele `.cpp`, deoarece aici merge vorba de creat „scheletul” proiectului. Implementările `.cpp` vor fi create în următoarea lucrare de laborator.

2024-09-04 13:11 UTC, cemti commented on labs/001/readme.ro.explaned.md
> +Pentru simplificarea procesului de lucru se propune să se efectueze pașii în mediul de dezvoltare `Visual Studio Code`, și cu compilatorul instalat `MingW G++`. De asemenea, pe calculator trebuie să
```suggestion
Pentru simplificarea procesului de lucru se propune să se efectueze pașii în mediul de dezvoltare [`Visual Studio Code`](https://code.visualstudio.com/Download), și cu compilatorul instalat [`MinGW G++`](https://sourceforge.net/projects/mingw-w64/). De asemenea, pe calculator trebuie să fie instalat [`Git`](https://git-scm.com/downloads).
```

2024-09-04 19:08 UTC, cemti approved these changes

2024-09-05 04:18 UTC, merged

2024-09-08 10:34 UTC, cemti commented
Să fie ștearsă ramura `lab/01`?

2024-09-08 10:52 UTC, mcroitor commented
> Să fie ștearsă ramura `lab/01`?

Da