lab02 is prepared
mcroitor/cpp_for_game_designers_ro pull request #3
Opened 2024-09-05 11:22 UTC by mcroitor

* lab02 is prepared
* fixed reference to the MinGW - MSYS system is proposed for usage

2024-09-05 15:32 UTC, cemti requested changes

2024-09-05 15:32 UTC, cemti commented on labs/002/readme.ro.explained.md
> +În directorul proiectului creați fișierul `Makefile` cu următorul conținut:
```suggestion
În directorul proiectului creați fișierul de construcție `Makefile` cu următorul conținut:

```

2024-09-05 15:32 UTC, cemti commented on labs/002/readme.ro.explained.md
Aici se arată implementarea goală a metodelor, ce poate duce la confuzii de către studenți.

2024-09-05 15:32 UTC, cemti commented on labs/002/readme.ro.md
>  3. Creați un fișier `cmd` (sau `Makefile`) pentru a construi manual proiectul
Se permite de utilizat un [wizard](https://learn.microsoft.com/en-us/cpp/build/reference/creating-a-makefile-project?view=msvc-170)?

2024-09-05 15:35 UTC, cemti commented on labs/002/readme.ro.explained.md
Poate de utilizat umpluturi de conținut de ex. `// ...` sau `// TODO: Insert logic here`.

2024-09-05 15:37 UTC, cemti commented
> * fixed reference to the MinGW - MSYS system is proposed for usage

De pe site:

> MSYS2 provides up-to-date native builds for GCC, mingw-w64

O propunere bună.

2024-09-05 15:59 UTC, mcroitor commented on labs/002/readme.ro.md
>  3. Creați un fișier `cmd` (sau `Makefile`) pentru a construi manual proiectul
Aici deja se permite

2024-09-05 16:46 UTC, mcroitor commented on labs/002/readme.ro.explained.md
La aceasta etapa corpul functiilor nu este important, Pot fi adaugate comentarii, dar ele precis o sa spuna ca in acest laborator se cere realizarea functiilor. Logica se implementeaza in lucrarea nr. 3.

2024-09-05 16:48 UTC, mcroitor commented on labs/002/readme.ro.explained.md
Anume ca in explicarea lab3 va fi data realizarea.

2024-09-05 16:51 UTC, cemti commented on labs/002/readme.ro.explained.md
Laboratorul 3 presupune ca scop doar să `redefinească operatori, precum și să se familiarizeze cu definiția și opțiunile de utilizare a constructorilor.`
Laboratorul 4 presupune de înlocuit structurile de date from scratch cu cele standarde.

Din această cauză, studenții cred că etapa corpul funcțiilor este important în această lucrare de laborator nr. 2.

2024-09-06 14:26 UTC, mcroitor commented on labs/002/readme.ro.explained.md
Problema consta in faptul ca e foarte complicat sa implementezi toate functii in timp de o saptamana sau doua. Oricum, in timpul lectiilor studentii o sa pun intrebari, si sarcina noastra de ghidat pe dansii si in acest caz.

2024-09-07 13:33 UTC, cemti approved these changes
Posibil ar merge așa.

2024-09-07 13:33 UTC, cemti commented on labs/002/readme.ro.explained.md
> +Point Apple::GetPosition() const {}
```suggestion
Apple::Apple() {/* ... */}
Apple::Apple(const Point &position) {/* ... */}
Point Apple::GetPosition() const {/* ... */}
```

2024-09-07 13:33 UTC, cemti commented on labs/002/readme.ro.explained.md
> +int Board::GetHeight() const {}
```suggestion
Board::Board(int width, int height) {/* ... */}
int Board::GetWidth() const {/* ... */}
int Board::GetHeight() const {/* ... */}
```

2024-09-07 13:33 UTC, cemti commented on labs/002/readme.ro.explained.md
> +void GameEngine::Run() {}
```suggestion
GameEngine::GameEngine() {/* ... */}
void GameEngine::Init() {/* ... */}
void GameEngine::Run() {/* ... */}
```

2024-09-07 13:33 UTC, cemti commented on labs/002/readme.ro.explained.md
> +void Painter::WriteText(Point position, char *text) {}
```suggestion
void Painter::DrawImage(Point topLeft, Point bottomRight, char **image) {/* ... */}
void Painter::WriteText(Point position, char *text) {/* ... */}
```

2024-09-07 13:33 UTC, cemti commented on labs/002/readme.ro.explained.md
> +void Snake::Eat(const Apple &apple) {}
```suggestion
Snake::Snake() {/* ... */}
Snake::Snake(const Point &_position) {/* ... */}
void Snake::Move(Direction direction) {/* ... */}
int Snake::GetSize() const {/* ... */}
Point Snake::GetPosition() const {/* ... */}
void Snake::Eat(const Apple &apple) {/* ... */}
```

2024-09-07 13:34 UTC, cemti commented
Mai sunt necesare schimbări?

2024-09-08 05:09 UTC, merged