lesson 1.2 translated
mcroitor/cpp_for_game_designers_ro pull request #4
Opened 2024-09-06 14:51 UTC by mcroitor

2024-09-06 19:47 UTC, cemti requested changes

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +- __signed__ - definește un tip de date ca fiind semnat
```suggestion
- __signed__ - definește un tip de date ca fiind cu semn
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +- __typedef__ - definește un tip de date nou
```suggestion
- __typedef__ - definește un sinonim pentru un tip de date existent
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +- __union__ - definește un tip de date care poate stoca mai multe tipuri de date
```suggestion
- __union__ - definește un tip de date care poate stoca mai multe tipuri de date în aceeași zonă de memorie
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +- __volatile__ - definește o variabilă ca fiind volatilă
```suggestion
- __volatile__ - definește o variabilă ca fiind modificabilă, în mod neprezicător, de factorii externi. Ca rezultat, se suprimă anumite optimizări de citire/înscriere asupra variabilei
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +În codul sursă pot fi incluse comentarii lineare și multiline.
```suggestion
În codul sursă pot fi incluse comentarii lineare și cu multe linii.
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +Comentarul multiline începe cu `/*` și se termină cu `*/`, între care se poate scrie orice număr de linii de text.
```suggestion
Comentariul cu multe linii începe cu `/*` și se termină cu `*/`, între care se poate scrie orice număr de linii de text.
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +- __char__ - tip de date pentru caractere, ocupă 1 byte în memorie. Poate stoca valori de la -128 la 127. Variabilele de tip char pot fi inițializate cu un singur caracter între ghilimele simple.
Diapazonul de valori pentru `char` este la alegerea liberă a compilatorului. `signed char` este garantat de la -128 la 127.

> `char` — type for character representation which can be most efficiently processed on the target system (has the same representation and alignment as either **signed char or unsigned char**, but is always a distinct type).

> The signedness of `char` depends on the compiler and the target platform: the defaults for ARM and PowerPC are typically unsigned, the defaults for x86 and x64 are typically signed.

https://en.cppreference.com/w/cpp/language/types#Character_types

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +Variabilele de tip `bool` ocupă 1 byte în memorie.
> `bool` — integer type, capable of holding one of the two values: true or false. The value of `sizeof(bool)` is implementation defined and might differ from 1.

https://en.cppreference.com/w/cpp/language/types#Boolean_type

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +    // comando 1
```suggestion
    // comanda 1
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +Tipul de date întors este tipul de date al rezultatului funcției. Dacă funcția nu returnează niciun rezultat, atunci tipul de date întors este `void`.
```suggestion
Tipul de date întors este tipul de date al rezultatului funcției. Dacă funcția nu returnează niciun rezultat, atunci tipul de date întors trebuie să fie `void`.
```

2024-09-06 19:47 UTC, cemti commented on 12_basics.md
> +Vectorii sunt structuri de date, care permit stocarea mai multor elemente de același tip. Vectorii se utilizează pentru stocarea unui număr mare de elemente de același tip.
```suggestion
Vectorii sunt structuri de date, care permit stocarea congruentă mai multor elemente de același tip. Vectorii se utilizează pentru stocarea unui număr mare de elemente de același tip.
```

2024-09-07 04:38 UTC, mcroitor commented on 12_basics.md
> +- identificatorul poate conține litere, cifre și simbolul de subliniere;
Penreu mine este destul de straniu, cum cineva poate sa incurca sublinierea cu minus sau tilda, dar lasa sa fie.

2024-09-09 17:20 UTC, cemti approved these changes
Văd că sunt unele conversații nerezolvate, dar merge și așa.

2024-09-09 17:53 UTC, mcroitor commented
> Văd că sunt unele conversații nerezolvate, dar merge și așa.

Am scapat acelea sugestii, am acceptat

2024-09-09 17:53 UTC, merged

2024-09-10 18:18 UTC, cemti commented
Ramura `12_basics` va fi ștearsă?
În viitor, voi șterge singur ramurile care au fost interclasate în `main`?