fixarea lab03
mcroitor/cpp_for_game_designers_ro pull request #5
Opened 2024-09-08 07:47 UTC by mcroitor

2024-09-08 13:28 UTC, cemti requested changes

2024-09-08 13:28 UTC, cemti commented on labs/003/readme.ro.explained.md
> +Point::Point(int _x, int _y) : x(_x), y(_y) {}
În `Point(int, int)`, nu are loc umbrirea câmpurilor `x` și `y`.
```suggestion
Point::Point() : x(), y() {}
Point::Point(int x, int y) : x(x), y(y) {}
```

2024-09-08 13:28 UTC, cemti commented on labs/003/readme.ro.explained.md
> +Board::Board(int width, int height) : _width(width), _height(height) {}
```suggestion
Board::Board() : _width(20), _height(20) {}
Board::Board(int width, int height) : _width(width), _height(height) {}
```

2024-09-08 13:28 UTC, cemti commented on labs/003/readme.ro.explained.md
> +Fixați modificările în depozitul local și trimiteți-le pe GitHub:
```suggestion
Fixați modificările în repozitoriul local și trimiteți-le pe GitHub:
```

2024-09-09 13:27 UTC, mcroitor commented on labs/003/readme.ro.explained.md
> +   Point operator = (const Point& other);
Anume aici eu nu sunt de acord. Eu inteleg de ce se propune intoarcerea referintei la obiect, si inteleg ca solutia mea creaza copierea adaugatoare, dar eu personal consider foarte neclar codul

```cpp
d = (a=b)+=c
```

sau

```cpp
(a=b)++
```

Eu prefer sa definesc operatori cu tip de intoarcere void, pentru a nu permite scrierea mai multor copieri intr-o linie. La urma urmei, accept intoarcerea copiei de obiect, nu referintei, pentru a proteje obiect de la modificari externe neevidente.

2024-09-09 17:27 UTC, cemti approved these changes

2024-09-10 16:30 UTC, merged

2024-09-10 18:16 UTC, cemti commented
Ramura `lab/03` va fi ștearsă?