3.1 projects translated
mcroitor/cpp_for_game_designers_ro pull request #9
Opened 2024-09-15 09:19 UTC by mcroitor

2024-09-15 13:15 UTC, cemti requested changes

2024-09-15 13:15 UTC, cemti commented on 31_projects.md
> +    g++-c main.cpp -O2 -std=c++14 -o main.o
```suggestion
file: first.o second.o main.o
    g++ first.o second.o main.o -o file -love
    
first.o: first.cpp
    g++ -c first.cpp -O2 -std=c++14 -o first.o

second.o: second.cpp
    g++ -c second.cpp -O2 -std=c++14 -o second.o

main.o: main.cpp
    g++ -c main.cpp -O2 -std=c++14 -o main.o
```

2024-09-15 13:15 UTC, cemti commented on 31_projects.md
> +CC = gcc
Văd că `$(CC)` este urmat de un fișier `.cpp`, nu `.c`.

```suggestion
CC = g++
```

2024-09-15 13:15 UTC, cemti commented on 31_projects.md
> +CC = gcc
```suggestion
CC = g++
```

2024-09-15 13:15 UTC, cemti commented on samples/12/extern/two.cpp
!?

2024-09-15 13:15 UTC, cemti commented on samples/12/function.cpp
> +    std::vector<int>::const_iterator it = number2.begin();
```suggestion
    std::vector<int>::const_iterator it = number2.cbegin();
```

2024-09-16 16:32 UTC, mcroitor commented on 31_projects.md
> +g++ first.o second.o main.o -o file -love
era in exemplu utilizarea librariei cu stimularea interesului studentilor

2024-09-16 16:34 UTC, mcroitor commented on 31_projects.md
> +CC = gcc
ok, dar `g++` este echivalent `gcc -lstdc++`

2024-09-16 16:36 UTC, mcroitor commented on samples/12/extern/two.cpp
acestea exemple au venit de la lectia de teorie, eu explicam notiuni ale limbajului

2024-09-16 16:37 UTC, mcroitor commented on 31_projects.md
> +- desfășurarea programului în mediul țintă,
este vorba de pereche platform+OS

2024-09-16 16:39 UTC, mcroitor commented on 31_projects.md
> +- automatizare condiționată (triggered automation): integrare continuă care efectuează o compilație la fiecare confirmare a modificării codului (commit) în sistemul de control al versiunilor.
aici eu aduc varianta engleza. Mai degraba trebuie (en. commit). Acum corectez peste tot.

2024-09-16 19:15 UTC, cemti approved these changes

2024-09-17 11:21 UTC, merged